// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALtbWWNDj54E1SrG1XscOleQpEKHufVwk',
    appId: '1:971088627127:web:823aca81a890390c3bd432',
    messagingSenderId: '971088627127',
    projectId: 'theologicalfactor',
    authDomain: 'theologicalfactor.firebaseapp.com',
    storageBucket: 'theologicalfactor.appspot.com',
    measurementId: 'G-N1TRM2ECE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBB8LVXZEmXmKrPvt1BxkbY3z2dKn-2Fg',
    appId: '1:971088627127:android:56023bc0ca3b0f483bd432',
    messagingSenderId: '971088627127',
    projectId: 'theologicalfactor',
    storageBucket: 'theologicalfactor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQU8RYy52loQwrTjAKQN51VU8_MCxPS6s',
    appId: '1:971088627127:ios:8ac6e4fa5bca010c3bd432',
    messagingSenderId: '971088627127',
    projectId: 'theologicalfactor',
    storageBucket: 'theologicalfactor.appspot.com',
    iosClientId: '971088627127-o9pr9nmq7mr51ggedvdm4f7rtbrvjnn4.apps.googleusercontent.com',
    iosBundleId: 'com.example.tfactors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQU8RYy52loQwrTjAKQN51VU8_MCxPS6s',
    appId: '1:971088627127:ios:8ac6e4fa5bca010c3bd432',
    messagingSenderId: '971088627127',
    projectId: 'theologicalfactor',
    storageBucket: 'theologicalfactor.appspot.com',
    iosClientId: '971088627127-o9pr9nmq7mr51ggedvdm4f7rtbrvjnn4.apps.googleusercontent.com',
    iosBundleId: 'com.example.tfactors',
  );
}
